apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-headers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-headers
  template:
    metadata:
      labels:
        app: echo-headers
    spec:
      containers:
        - name: echo-headers
          image: registry.digitalocean.com/rocks-network/echo-headers:v1.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
